// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/ocuroot/ui/components/navbar"
)

// ShowcaseNavbar creates a consistent navbar for all showcase pages
func ShowcaseNavbar(activePage string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = navbar.Navbar(navbar.NavbarConfig{
			BrandName: "Ocuroot",
			BrandURL:  "/",
			LogoURL:   "/static/logo.svg",
			Items: []navbar.NavItem{
				navbar.NavLink{
					Name:   "Modal Components",
					URL:    "/modal",
					Active: activePage == "modal",
				},
				navbar.NavLink{
					Name:   "Table Components",
					URL:    "/table",
					Active: activePage == "table",
				},
				navbar.NavLink{
					Name:   "Docs",
					URL:    "/docs/intro",
					Active: activePage == "docs",
				},
				navbar.NavDropdown{
					ID:   "showcase",
					Name: "Showcase",
					Items: []navbar.DropdownItem{
						{Name: "Tabs", URL: "/components#tabs"},
						{Name: "Badges", URL: "/components#badges"},
						{Name: "Hero Sections", URL: "/components#hero"},
						{Name: "Progress", URL: "/components#progress"},
						{Name: "Links", URL: "/components#links"},
						{Name: "Icons", URL: "/components#icons"},
						{Name: "Forms", URL: "/components#forms"},
					},
				},
				navbar.NavLink{
					Name:   "All Components",
					URL:    "/components",
					Active: activePage == "components",
				},
				navbar.NavLink{
					Name:   "Social Cards",
					URL:    "/social-card",
					Active: activePage == "social-card",
				},
				navbar.NavComponent{
					Component: NavComponentExample(),
				},
			},
			ShowThemeToggle: true,
			ShowUserMenu:    false,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func NavComponentExample() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex gap-4 items-center\"><a class=\"flex flex-col items-center gap-2 bg-transparent rounded p-2 hover:bg-gray-100\" href=\"/components#buttons\"><svg class=\"h-4 w-4 text-white\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle> <line x1=\"12\" y1=\"3\" x2=\"12\" y2=\"12\"></line> <line x1=\"12\" y1=\"21\" x2=\"12\" y2=\"21\"></line></svg></a> <a class=\"flex flex-col items-center gap-2 bg-transparent rounded p-2 hover:bg-gray-100\" href=\"/components#alerts\"><svg class=\"h-4 w-4 text-white\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"2\" y=\"7\" width=\"20\" height=\"10\" rx=\"2\"></rect> <polyline points=\"2 12 22 2 12 22\"></polyline></svg></a> <a class=\"flex flex-col items-center gap-2 bg-transparent rounded p-2 hover:bg-gray-100\" href=\"/components#breadcrumbs\"><svg class=\"h-4 w-4 text-white\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 2L2 7l10 5 10-5\"></path> <path d=\"M2 17l10 5 10-5M2 12l10 5 10-5\"></path></svg></a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
